title = "configuration in train mode"

[general]
    data_path = ""
    H = 128
    batch_size = 60
    num_workers = 4
    shuffle = true
    start_epoch = 0
    epochs = 120
    test_times = 1
    max_iter = 10000

    max_search_iter = 30
    max_samples = 30000

    num_cfr = 1

[model]
    load = false
    freeze = false
    load_path = "./checkpoint_20.pt"
    save_path = "./"
    save_iter = 10

[hyperparameters]
    lr = 1e-3
    betas = 0.9
    decay = 1e-4